-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 11:06:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_eventReg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_eventReg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_eventReg` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb_eventregistration
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_eventregistration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_eventregistration` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb_eventReg` ;

-- -----------------------------------------------------
-- Table `mydb_eventReg`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`roles` (
  `idroles` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_eventReg`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `roles_idroles` INT NOT NULL,
  `status` ENUM('aktif', 'tidak aktif') NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb_eventReg`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_eventReg`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`events` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `location` VARCHAR(255) NULL,
  `speaker` VARCHAR(255) NULL,
  `poster` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NULL,
  `max_participants` INT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_users1_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb_eventReg`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_eventReg`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`payments` (
  `id` INT NOT NULL,
  `registration_id` INT NULL,
  `uploaded_by` INT NULL,
  `proof_path` VARCHAR(255) NULL,
  `verified_by` INT NULL,
  `status` ENUM('pending', 'verified', 'rejected') NULL,
  `verified_at` TIMESTAMP NULL,
  `uploaded_at` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb_eventReg`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_eventReg`.`event_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`event_registration` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `registered_at` TIMESTAMP NULL,
  `qr_code` VARCHAR(255) NULL,
  `events_id` INT NOT NULL,
  `payments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_registration_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_event_registration_events1_idx` (`events_id` ASC) VISIBLE,
  INDEX `fk_event_registration_payments1_idx` (`payments_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_registration_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb_eventReg`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_registration_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `mydb_eventReg`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_registration_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `mydb_eventReg`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_eventReg`.`event_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventReg`.`event_attendance` (
  `id` INT NOT NULL,
  `registration_id` INT NULL,
  `scanned_by` INT NULL,
  `scanned_at` TIMESTAMP NULL,
  `event_registration_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_attendance_event_registration1_idx` (`event_registration_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_attendance_event_registration1`
    FOREIGN KEY (`event_registration_id`)
    REFERENCES `mydb_eventReg`.`event_registration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb_eventregistration` ;

-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`cache` (
  `key` VARCHAR(255) NOT NULL,
  `value` MEDIUMTEXT NOT NULL,
  `expiration` INT(11) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`cache_locks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`cache_locks` (
  `key` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `expiration` INT(11) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive') NULL DEFAULT 'active',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb_eventregistration`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `speaker` VARCHAR(255) NULL DEFAULT NULL,
  `poster` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `max_participants` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(4) NULL DEFAULT 1,
  `created_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb_eventregistration`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`payments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `registration_id` INT(11) NOT NULL,
  `uploaded_by` INT(11) NULL DEFAULT NULL,
  `proof_path` VARCHAR(255) NULL DEFAULT NULL,
  `verified_by` INT(11) NULL DEFAULT NULL,
  `status` ENUM('pending', 'verified', 'rejected') NULL DEFAULT 'pending',
  `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `verified_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `registration_id` (`registration_id` ASC) VISIBLE,
  INDEX `uploaded_by` (`uploaded_by` ASC) VISIBLE,
  INDEX `verified_by` (`verified_by` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`registration_id`)
    REFERENCES `mydb_eventregistration`.`event_registration` (`id`),
  CONSTRAINT `payments_ibfk_2`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `mydb_eventregistration`.`users` (`id`),
  CONSTRAINT `payments_ibfk_3`
    FOREIGN KEY (`verified_by`)
    REFERENCES `mydb_eventregistration`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`event_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`event_registration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `registered_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `qr_code` VARCHAR(255) NULL DEFAULT NULL,
  `payment_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id` (`event_id` ASC) VISIBLE,
  INDEX `users_id` (`users_id` ASC) VISIBLE,
  INDEX `fk_payment_id` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `event_registration_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb_eventregistration`.`events` (`id`),
  CONSTRAINT `event_registration_ibfk_2`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb_eventregistration`.`users` (`id`),
  CONSTRAINT `fk_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb_eventregistration`.`payments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`event_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`event_attendance` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `registration_id` INT(11) NOT NULL,
  `scanned_by` INT(11) NULL DEFAULT NULL,
  `scanned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `registration_id` (`registration_id` ASC) VISIBLE,
  INDEX `scanned_by` (`scanned_by` ASC) VISIBLE,
  CONSTRAINT `event_attendance_ibfk_1`
    FOREIGN KEY (`registration_id`)
    REFERENCES `mydb_eventregistration`.`event_registration` (`id`),
  CONSTRAINT `event_attendance_ibfk_2`
    FOREIGN KEY (`scanned_by`)
    REFERENCES `mydb_eventregistration`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`job_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`job_batches` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_jobs` INT(11) NOT NULL,
  `pending_jobs` INT(11) NOT NULL,
  `failed_jobs` INT(11) NOT NULL,
  `failed_job_ids` LONGTEXT NOT NULL,
  `options` MEDIUMTEXT NULL DEFAULT NULL,
  `cancelled_at` INT(11) NULL DEFAULT NULL,
  `created_at` INT(11) NOT NULL,
  `finished_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT(3) UNSIGNED NOT NULL,
  `reserved_at` INT(10) UNSIGNED NULL DEFAULT NULL,
  `available_at` INT(10) UNSIGNED NOT NULL,
  `created_at` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb_eventregistration`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_eventregistration`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NOT NULL,
  `last_activity` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sessions_user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `sessions_last_activity_index` (`last_activity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
